kind: Pod
apiVersion: v1
metadata:
   name: testpod
spec:
  containers:
     - name: c1
       image: ubuntu
       command: ["/bin/bash", "-c", "while true; do echo Technical-Guftgu; sleep 5 ; done"]
       env:
         - name: MYENV
           valueFrom:
             configMapKeyRef:
               name: mymap
               key: sample.conf
            
