apiVersion: v1
kind: Pod
metadata:
  name: secret-pod
  labels:
    name: configpod
spec:
  containers:
    - name: c1
      image: ubuntu
      command: ["/bin/bash", "-c", "while true; do echo Technical-Guftgu; sleep 5; done"]
      volumeMounts:
        - name: sectvol
          mountPath: /tmp/sectvol
  volumes:
    - name: sectvol
      secret:
        secretName: mysecret

