kind: Service
apiVersion: v1
metadata:
  name: service-test
spec:
  selector:
    app: mydeploy  # Ensure this matches labels in your Pods/Deployment
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP  # Fixed uppercase 'P'
