apiVersion: v1
kind: Pod
metadata:
  name: testpod
spec:
  containers:
    - name: c1
      image: ubuntu
      command: ["/bin/bash", "-c", "while true; do echo sonu; sleep 5; done"]
      resources:
        requests:  # Fixed from 'request'
          memory: "200Mi"
          cpu: "50m"
        
