kind: Pod
apiVersion: v1
metadata:
   name: testpod
spec:
   containers:
      - name: c1
        image: ubuntu
        command: ["/bin/bash", "-c", "while true; do echo Running...; sleep 5; done"]
        resources:
           requests:
              memory: "30Mi"
              cpu: "50m"
           limits:
              memory: "60Mi"
              cpu: "70m" 

